### ISSUE TITLE
Coursework feedback

### ISSUE THREAD

**Issue by NYBACHOK** [mverbytska/markdown_parser#1]
Student: Вербицька Марія

Для прохідного:
! CLI: ✔️
! Brief Description: ✔️
! Project Name: ✔️
! Grammar Rules: ✔️
! Unit Tests: ✔️
! Core Files: ✔️

Для мааксимального:
File System: ❌ не бачу запис у файл
Test Coverage: ✔️
Error Handling: ❌ thisserror -> main.rs && lib.rs , anyhow -> tests
cargo fmt: ✔️
cargo clippy: ✔️
makefile: ✔️
Completeness: ❌
Including a diagram or grammar in the Readme.md:  ❌
Documentation: ✔️
Publishing ❌

Курсова може бути зарахована ✔️
Бал: 15/25

**Comment by mverbytska** [comment]
> Student: Вербицька Марія
> 
> Для прохідного: ! CLI: ✔️ ! Brief Description: ✔️ ! Project Name: ✔️ ! Grammar Rules: ✔️ ! Unit Tests: ✔️ ! Core Files: ✔️
> 
> Для мааксимального: File System: ❌ не бачу запис у файл Test Coverage: ✔️ Error Handling: ❌ thisserror -> main.rs && lib.rs , anyhow -> tests cargo fmt: ✔️ cargo clippy: ✔️ makefile: ✔️ Completeness: ❌ Including a diagram or grammar in the Readme.md: ❌ Documentation: ✔️ Publishing ❌
> 
> Курсова може бути зарахована ✔️ Бал: 15/25

Добрий вечір! Дякую за фідбек, мене влаштовує поточний бал!)

**Comment by NYBACHOK** [comment]
Привіт. Зверни увагу, що дедлайн був минулої середи, тому бал може виявитися нижчим

**Comment by mverbytska** [comment]
> Привіт. Зверни увагу, що дедлайн був минулої середи, тому бал може виявитися нижчим

Добрий вечір. Так я розумію, я погоджуюсь на цю оцінку. Дякую!
